services:
  - type: web
    name: portfolio-backend
    runtime: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        scope: runtime
      - key: FRONTEND_URL
        sync: false
      - key: MAIL_SERVICE
        value: gmail
      - key: MAIL_USER
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: ADMIN_EMAIL
        sync: false
